blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    #ex: /blog/
    url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<slug>[\w.-]+)/$', views.PostView.as_view(), name="post"),
]

contactpage/urls.py
from django.contrib import admin
from django.conf.urls import url

from . import views

app_name = 'contact'
urlpatterns = [
    url(r'^$', views.emailView, name='email'),
    url(r'success/', views.successView, name='success'),
]

home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    #url(r'^projects/$', views.ProjectsView.as_view(), name='projects'),
]

isaacwebsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

#from filebrowser.sites import site
#from filebrowser.storage import S3BotoStorageMixin
#from django.core.files.storage import default_storage

#if FileSystemStorageMixin not in default_storage.__bases__:
#    default_storage.__bases__ += (FileSystemStorageMixin,)

#site.storage = default_storage

urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^projects/', include('projects.urls')),
    url(r'^contact/', include('contactpage.urls')),
]

projects/urls.py
from django.conf.urls import url

from . import views

app_name = 'projects'
urlpatterns = [
    #ex: /blog/
    url(r'^$', views.ProjectListView.as_view(), name='project_list'),
    url(r'^(?P<slug>[\w.-]+)/$', views.ProjectView.as_view(), name="project"),
]

blog/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime  
from django.contrib.auth.models import User
#from .admin import MyModelAdmin

class Post(models.Model):
    author = models.ForeignKey(User, models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=40)
    #body = "/blogposts/{}.html".format(title)
    pub_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.pub_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title
    
    def get_date(self):
        time = datetime.now()
        if self.pub_date.day == time.day:
            if (time.hour - self.pub_date.hour)==1:
                return str(time.hour - self.pub_date.hour) + " hour ago"
            else:
                return str(time.hour - self.pub_date.hour) + " hours ago"
        else:
            if self.pub_date.month == time.month:
                if (time.day - self.pub_date.day)==1:
                    return str(time.day - self.pub_date.day) + " day ago"
                else:
                    return str(time.day - self.pub_date.day) + " days ago"
            else:
                if self.pub_date.year == time.year:
                    if (time.month - self.pub_date.month)==1:
                        return str(time.month - self.pub_date.month) + " month ago"
                    else:
                        return str(time.month - self.pub_date.month) + " months ago"
                else:
                    if (time.year - self.pub_date.year)==1:
                        return str(time.year - self.pub_date.year) + " year ago"
                    else:
                        return str(time.year - self.pub_date.year) + " years ago"
        return self.pub_date

contactpage/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime
from django.contrib.auth.models import User
#from .admin import MyModelAdmin

class Project(models.Model):
    author = models.ForeignKey(User, models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=40, blank=True, null=True)
    #body = "/blogposts/{}.html".format(title)
    pub_date = models.DateTimeField(blank=True, null=True)
    external_link = models.CharField(blank=True, null=True, max_length=200)

    def publish(self):
        self.pub_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title
    
    def get_date(self):
        time = datetime.now()
        if self.pub_date.day == time.day:
            if (time.hour - self.pub_date.hour)==1:
                return str(time.hour - self.pub_date.hour) + " hour ago"
            else:
                return str(time.hour - self.pub_date.hour) + " hours ago"
        else:
            if self.pub_date.month == time.month:
                if (time.day - self.pub_date.day)==1:
                    return str(time.day - self.pub_date.day) + " day ago"
                else:
                    return str(time.day - self.pub_date.day) + " days ago"
            else:
                if self.pub_date.year == time.year:
                    if (time.month - self.pub_date.month)==1:
                        return str(time.month - self.pub_date.month) + " month ago"
                    else:
                        return str(time.month - self.pub_date.month) + " months ago"
                else:
                    if (time.year - self.pub_date.year)==1:
                        return str(time.year - self.pub_date.year) + " year ago"
                    else:
                        return str(time.year - self.pub_date.year) + " years ago"
        return self.pub_date

contactpage/forms.py
from django import forms

class ContactForm(forms.Form):
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

blog/views.py
#from django.shortcuts import render
from django.views import generic
from django.utils import timezone

from .models import Post

class PostListView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'latest_post_list'
    
    def get_queryset(self):
        """Return the last five published blog posts"""
        return Post.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    
class PostView(generic.DetailView):
    model = Post
    slug_field = 'slug'
    template_name = 'blog/detail.html'
    
    def get_queryset(self):
        """
        Excludes any blog posts that aren't published yet.
        """
        return Post.objects.filter(pub_date__lte=timezone.now())

contactpage/views.py
# sendemail/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm
import os

def emailView(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, [os.environ['EMAIL_ADDRESS']], fail_silently=False)
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('contact:success')
    return render(request, "contactpage/index.html", {'form': form})

def successView(request):
    template_name = 'contactpage/success.html'
    return HttpResponse(render(request, "contactpage/success.html"))

home/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.

class IndexView(generic.TemplateView):
    template_name = 'home/index.html'

projects/views.py
#from django.shortcuts import render
from django.views import generic
from django.utils import timezone

from .models import Project

class ProjectListView(generic.ListView):
    template_name = 'projects/index.html'
    context_object_name = 'latest_project_list'
    
    def get_queryset(self):
        """Return the last five published project posts"""
        return Project.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    
class ProjectView(generic.DetailView):
    model = Project
    slug_field = 'slug'
    template_name = 'projects/detail.html'
    
    def get_queryset(self):
        """
        Excludes any project posts that aren't published yet.
        """
        return Project.objects.filter(pub_date__lte=timezone.now())

blog/templates/blog/detail.html
{% extends 'layouts/base.html' %}

{%load template_extras%}

{% block extra_head %} 
{% load static %}
<title>{{post.title}}</title>
<link rel="stylesheet" type="text/css" href="{% static 'layouts/base.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'blog/blog.css' %}" />
<script src="https://d3js.org/d3.v5.min.js"></script>
{% endblock %}

{% block content %}

<h1 class=post_title>{{ post.title }}</h1>

<!--{% if error_message %}<p><strong> {{ error_message }} </strong></p> {% endif %}

<p> {{ blog.text }} </p>-->

{% with "blogposts/"|addstr:post.title|addstr:".html" as post_html%}
{%include_fallback post_html "utils/blank.html"%}
{% endwith %}

{% endblock %}

{% block ga %}
{% if GA_TRACKING_ID %}
  {% include "layouts/scripts/ga.html" %}
{% endif %}
{% endblock %}

blog/templates/blog/index.html
{% extends 'layouts/base.html' %}

{% block extra_head %} 
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/blog.css' %}" />
{% endblock %}

{% block content %}
{% if latest_post_list %}

<div class=post_list>
    <nav>
        <ul>
        {% for post in latest_post_list %}
            <li>
                <h3><a href="{% url 'blog:post' post.slug%}"> {{ post.title }} </a></h3>
                <p class='pub_date'> {{ post.get_date }} </p>
            </li>
        {% endfor %}
        </ul>
    </nav>
</div>
{% else %}
    <p> No blog posts are available </p>
{% endif %}

{% endblock %}

{% block ga %}
{% if GA_TRACKING_ID %}
  {% include "layouts/scripts/ga.html" %}
{% endif %}
{% endblock %}

blog/templates/blogposts/2018 Goals.html
<div class="cell border-box-sizing text_cell rendered">
<div class="prompt input_prompt">
</div>
<div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<p>2018 is going to be a great year. It's the year I change my name from Isaac Layton to Mr. Husband Isaac Layton. I'm going to be marrying the love of my life in May. I'm going to run a half marathon in April, and I'm going to try to run a triathlon in September. I want to read the whole Bible this year. Along with these ambitions, I have goals for improving myself in data science as well.</p>

</div>
</div>
</div>
<div class="cell border-box-sizing text_cell rendered">
<div class="prompt input_prompt">
</div>
<div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<h2 id="Read-at-least-half-of-The-Elements-of-Statistical-Learning">Read at least half of <a href="https://web.stanford.edu/~hastie/ElemStatLearn/">The Elements of Statistical Learning</a><a class="anchor-link" href="#Read-at-least-half-of-The-Elements-of-Statistical-Learning">&#182;</a></h2><p>I love this book, but only managed to get to Chapter 3 before getting sidetracked. I want to get a lot farther this upcoming year. This is a book that I don't mind taking my time through though, because of how jam packed it is with information. If I only get through a few chapters I'll still be satisfied.</p>

</div>
</div>
</div>
<div class="cell border-box-sizing text_cell rendered">
<div class="prompt input_prompt">
</div>
<div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<h2 id="Finish-CS224N,-Stanford's-class-on-Natural-Language-Processing">Finish CS224N, Stanford's class on Natural Language Processing<a class="anchor-link" href="#Finish-CS224N,-Stanford's-class-on-Natural-Language-Processing">&#182;</a></h2><p>In May, I started going through this course and really enjoyed learning about NLP in the context of deep learning. I'd like to spend a month or two finishing it.</p>

</div>
</div>
</div>
<div class="cell border-box-sizing text_cell rendered">
<div class="prompt input_prompt">
</div>
<div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<h2 id="One-project-per-month">One project per month<a class="anchor-link" href="#One-project-per-month">&#182;</a></h2><p>For this goal, I'd like to have a diversity of projects that focus on a specific subset of statistics or programming that I'm learning about. It could be about the NLP class, about a topic in Elements of Statistical Learning, or about some dataset I'm interested in learning about.</p>

</div>
</div>
</div>
<div class="cell border-box-sizing text_cell rendered">
<div class="prompt input_prompt">
</div>
<div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">
<p>I'll try to post in my blog about these projects and what I aim on doing each month.</p>

</div>
</div>
</div>

blog/templates/blogposts/Collecting Website Files Automatically with Cron.html
<div class='text'>

    <p>A few months ago, I wanted to know why a swarm of police cars were rushing down the street I was driving on. While I was searching for the reason, I discovered that my local police department puts up a new police report log on their website every Monday through Friday. The previous log is taken down when the current log is put up, so I've been meaning to figure out how to download the log into a folder, with the intent of eventually analyzing the data.</p>

    <p>I learned how to do this a week ago, so I'll let you in on the secret! The process I'm using is to extract police log data, but you could use it to extract any kind of file that is put up daily. </p>

    <h2>Step 1: Find a server</h2>

    <p>While you could end up using your computer to automate the process, you'd be more prone to problems. Your computer would have to be awake at the same time every day for the processes to run. If you have to wake your computer up at the same time every day, it kind of takes away the beauty of automation. You can keep a server running 24/7 if needed.</p>

    <p>This step could have it's own article dedicated to it. There are a lot of different options, such as DigitalOcean droplets and Windows Azure virtual machines. In this article, I'll be using one of Amazon Web Services' EC2 instances. They're what I'm most familiar with and are pretty easy to set up. Plus, if you've never used Amazon Web Services (AWS) before, you get a <a href="https://aws.amazon.com/free/">year of their free tier</a>). To learn how to set up an EC2 instance, you can read AWS' <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EC2_GetStarted.html">EC2 User Guide</a>.</p>

    <p>The Amazon Machine Image I chose was the "Ubuntu Server 16.04 LTS (HVM), SSD Volume Type". I then chose to make it a t2.nano instance type because downloading a single file every day isn't very intensive, and the t2.nano is the smallest instance that Amazon offers in terms of memory and processing power. As part of the free tier though, you get 750 hours/month free of t2.micro instances. That's 31.25 days, meaning you don't ever have to stop it. Choosing this type might make more sense if this is your only EC2 instance.  Once you have your server activated, you can log into it by following steps 2-4 of <a href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstancesLinux.html">these instructions</a>. </p>

    <h2>Step 2: Wget the wdata <sup><a href='#fn1' id='ref1'>1</a></sup></h2>

    <p>Now that the server is up and running, you need to be able to get the desired file from its website to your server from the command line. The command needed for this is "wget". Wget ("web get") is a Linux/Unix command that downloads a file from a given source. The syntax for this is: </p>

    <div class="codebox">
        <code>
            user@server:/$ wget www.website.com/file.txt -O log.txt</code>
    </div>

    <p>The -O is the letter O not the number 0. The reason it's there is so that you can rename the file to what you want to call it (in this example, as <code>log.txt</code>). The filename doesn't have to change, but it'll be helpful for when we want the filename to reflect a different day or revision. If the website putting up the file already specifies a date/revision when putting it up, you could skip this step, although it would be safe to also version it yourself.</p>

     <p>The way that we're going to version it is as follows:</p>

    <div class="codebox">
        <code>
            user@server:/$ wget www.website.com/file.txt -O log_$(date +%Y%m%d).txt</code>
    </div>

    <p><code>$(date +%Y%m%d)</code> is a <a href="http://www.compciv.org/topics/bash/variables-and-substitution/">command substitution</a>, which means that it'll run the <code>date</code> command in the format YYYYMMDD (e.g. 20181231) and append it to the end of our filename.

    <p>We now have a way of getting the data from the website directly into our server. The next step is deciding where to store it. </p>

    <h2>Step 3: Storing the Data</h2>

    <p>If your server has a lot of storage and the files you're collecting are small, you could just keep the files on your server. If you choose to do this and use the server for other purposes, you should store them in a folder with an appropriate name. The command <code>mkdir foldername</code> will create the folder. Instead of using <code>wget</code> to put the file at <code>filename.txt</code>, put it at <code>foldername/filename.txt</code>.</p>

    <p>The EC2 server I was using didn't have a lot of storage, so I needed to find a different solution. I decided to transfer the files using an S3 bucket. S3 is another service that AWS offers specifically for storage purposes. You can read about setting an S3 bucket up using <a href="https://docs.aws.amazon.com/AmazonS3/latest/gsg/CreatingABucket.html">these instructions</a>. There are a lot of different customizations for S3 buckets, but the default settings will be fine.</p>

    <p>Once your S3 bucket is set up, you'll need to download the <a href='https://aws.amazon.com/cli/'>AWS Command Line Interface (CLI)</a>. This will allow you to access your S3 bucket from the command line. To download the AWS CLI, execute the following commands:</p>

    <div class="codebox">
        <code><pre>
        user@server:/$ sudo apt-get update && sudo apt-get -y upgrade
        user@server:/$ sudo apt-get install python-pip
        user@server:/$ pip install awscli --upgrade --user</pre></code>
    </div>
    
    <p>The AWS CLI needs to be configured so that it knows to use your AWS account. To start with, you'll need to create an IAM user for your AWS account. The instructions for doing that <a href='https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html'>are here</a>. Give the user programmatic access and under permissions give it "AmazonS3FullAccess". Once created, follow the instructions <a href='https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html'>here</a> to create a access key ID and secret access key for your IAM user and finish the configuration. </p>
    
    <p>You now have everything in place to transfer the file from your server to your S3 bucket. The command for doing this will be:</p>
    
    <div class='codebox'>
        <code>
            user@server:/$ aws s3 cp log_$(date +%Y%m%d).txt s3://yourBucketName
        </code>
    </div>
    
    <p>The <code>s3 cp</code> function is used to copy files from your directory to the specified bucket. If you check your S3 bucket after running this, you should see the file!</p>
    
    <h2>Step 4: Automating the Process</h2>
    
    <p>Now that we've managed to download the data and store it appropriately, it's time to make the server do it on its own. The way we're going to do this is by using cron. <a href='http://www.unixgeeks.org/security/newbie/unix/cron-1.html'>Cron</a> is a command line program used to schedule tasks. To use cron, you're going to edit your configuration file, known as crontab. Entering <code>crontab -e</code> will open the file to be edited. The syntax for each automated command or "cron job" is as follows:</p>
    
    <div class='codebox'>
        <code><pre class='cron'>
        <span class='cron'></span><i>your command</i>
        </pre></code>
    </div>
    
    <p>If you hover over each asterisk, you can see what time value it represents. If you don't use a value, you can leave it as an asterisk. The values can be ranges as well, using a hyphen to signify a range. For example, <br/> <code>00 23 * * 1-5 echo "hi"</code> would print "hi" Monday through Friday at 23:00 (11:00pm) UTC time. </p>
    
    <p>We're going to use cron to execute 3 tasks:</p>
    <ol>
        <li>We're going to retrieve the data like we did in Step 2.</li>
        <li>We're going to store the data like we did in Step 3.</li>
        <li>We're going to delete the file off of the server to save space (this command isn't needed if you opted to keep the files on your server).</li>
    </ol>
    <p>When we put all of these together in the crontab file, it's going to look like this:</p>
    
    <div class="codebox">
        <code><pre>
        00 23 * * 1-5 /usr/bin/wget www.website.com/file.txt -O log_$(date +\%Y\%m\%d).txt
        01 23 * * 1-5 .local/bin/aws s3 cp log_$(date +\%Y\%m\%d).txt s3://yourBucket
        02 23 * * 1-5 rm log_$(date +\%Y\%m\%d).txt</pre></code>
    </div>
    
    <p>There are a few things to note about this:</p>
    <ul>
        <li>We used <code>/usr/bin/wget</code> and <code>.local/bin/aws</code> instead of just <code>wget</code> and <code>aws</code>. Cron needs absolute pathnames so that it knows where to find the program. To find out where your programs are located, use the command <code>which programName</code> and it will give you the absolute pathname. If it starts with something like /home/user/, disregard that section of the pathname because the crontab file you're using is already associated with your user.</li>
        <li>There are backslashes before the percent signs in the date section of the output file's name. This is because cron uses the percent sign to mean a new line. The backslashes will let us escape this interpetation.</li>
        <li>We could've put these commands into a <a href='https://ryanstutorials.net/bash-scripting-tutorial/bash-script.php'>bash script</a>, but since there are only 3 lines, it felt unnecessary.</li>
        <li>I decided to separate the commands by a minute each, but using the <a href='https://stackoverflow.com/questions/4510640/what-is-the-purpose-of-in-a-shell-command'>'&&' syntax</a> of running the commands sequentially would have also worked. </li>
    </ul>
    
    <p>Once this is in your crontab file, press CTRL-X to exit the program. If you check in a day or two, you should see a file or two in your S3 bucket or server folder! </p>
    
    <h2>Conclusion</h2>
    
    <p>The data has been collecting for about a couple weeks now. I plan on letting it sit for a few months and then analyzing the results. Thanks for reading this half blog post/half tutorial and check back in a few months to see if I've created a project around this!</p>
    
</div>

<div id='footnotes'>
<sup id='fn1'>1. This is a bad wget joke, there's no such thing as wdata as far as I'm aware. There's also no such thing as a good wget joke.<a href='#ref1' title='Get back to reading'>↩</a></sup>
</div>

<script>
    const arr = ['minute (0 - 59)', 'hour (0-23)', 'day of the month (1-31)', 'month (1-12)', 'day of the week (0-6 with 6 being Sunday)'];
    let div = d3.select('pre.cron').append('div')
            .attr('class', 'tooltip')
            .style('opacity', 0)
            .style('height', '25px');
    d3.select('span.cron').selectAll('span.options')
        .data(arr)
        .enter()
        .append('span')
        .attr('class', 'options')
        .text((d)=>'*')
        .style('padding-left', (d,i)=>i==0 ? '0px' : '10px')
        .style('padding-right', (d,i)=>i==4 ? '20px' : '10px')
    d3.selectAll('span.options')
        .on('mouseover', mouseover)
        .on('mouseout', mouseout)
    
    function mouseover(d,i) {
        div.style('opacity', .9)
        div.transition().duration(200);
        div.html(d)
        div.style('padding-left', i*30 + 'px')
    }
    
    function mouseout() {
        div.transition()
            .duration(500)
            .style('opacity',0)
    }
</script>

blog/templates/blogposts/Welcome to isaaclayton.com.html
<p>Hi! Thanks for visiting my website. It's been my main project for the past couple months and I'm really eager to get it started.</p>

<h2>What I want to accomplish</h2>

<p>My website is still a work in progress and will continuously be improving as I learn what works and what doesn't. Ideally this website will be around for awhile, so I have some short term goals and long term goals in mind for it.</p>

<h3>Short Term Goals</h3>

<ul>
    <li>
        <p><strong>Figure out how I want this website to look.</strong> Part of this process is getting reacquainted with HTML and
            CSS. The last time that I was creating websites was in high school. I'm using Django as the framework because of its
            functionality with Python, but I could be switching to a different framework down the road. I want to keep the website
            looking somewhat simple, as I want to spend most of my time on projects.</p>
    </li>
    <li>
        <p><strong>Create small JavaScript learning projects.</strong> I want to make posts/pages that let users interact with
            them. I'll probably start off with small posts that try out different APIs and JavaScript libraries.</p>
    </li>
    <li>
        <p><strong>Publish past projects on my project page.</strong> I have a handful of projects, including my senior project,
            that I want to put up. Some of them are only partially complete though, so the first step in this goal will be
            finishing up any loose ends.</p>
    </li>
</ul>
<h3>Long Term Goals</h3>

<ul>
    <li>
        <p><strong>Keep up with data science.</strong> This is the main purpose of this blog. One of my dreams is to pursue a
            career in machine learning/data science. Because of having a full-time job, I've been on and off with my data science
            learning. And as with any skill, practice is essential. I plan on completing projects related to what I'm learning at
            the time. Some topics that I plan on learning more about are NLP (natural language processing), data visualization,
            neural networks, evolutionary algorithms, generative adversarial networks, and reinforcement learning.</p>
    </li>
    <li>
        <p><strong>Get better at web development.</strong> I'm definitely not using Django to its potential, so I plan on learning
            more of its features so that I can make my site quick, efficient, and appealing. Along with Django, I want to learn
            d3.js, React, and jQuery. That list might end up changing throughout the next few months.</p>
    </li>
    <li>
        <p><strong>Archive my work.</strong> I've learned a lot and done a lot of projects in the past 3-4 years. Unfortunately, a
            lot of the work is scattered deep in folders I've long since touched. I'd like to be able to showcase my work to
            others, as well as have a place that I can go to where I can look back at my past work. It'd be especially neat if
            someone was able to leave my site having learned something new.</p>
    </li>
</ul>

projects/templates/projects/detail.html
{%load template_extras%}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <title>{{ project.title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'layouts/projects.css' %}" />
</head>
<body>
    
{% with "project_files/"|addstr:project.slug|addstr:"/index.html" as project_html%}
{%include_fallback project_html "utils/blank.html"%}
{% endwith %}  
    
</body>
 <footer>
     <div class='menu'>
         <nav>
             <a href="{% url 'home:index' %}">About</a>
             <a href="{% url 'projects:project_list' %}">Projects</a>
             <a href="{% url 'blog:post_list' %}">Blog</a>
             <a href="{% static 'pdf_files/resume.pdf' %}">Resume</a>
             <a href="{% url 'contact:email' %}">Contact</a>
         </nav>
     </div>
     <br/>
     <p>&copy; Isaac Layton 2018.</p>
      
</footer>
</html>
{% block ga %}
{% if GA_TRACKING_ID %}
  {% include "layouts/scripts/ga.html" %}
{% endif %}
{% endblock %}

projects/templates/projects/index.html
{% extends 'layouts/base.html' %}

{% block extra_css %} 
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/blog.css' %}" />
{% endblock %}

{% block content %}
{% if latest_project_list %}

<div class=post_list>
    <nav>
        <ul>
        {% for project in latest_project_list %}
            <li>
                {% if project.external_link == None %}
                    <h3><a href="{% url 'projects:project' project.slug%}"> {{ project.title }} </a></h3>
                {% else %}
                    <h3><a href={{ project.external_link }} target='_blank'> {{ project.title }} </a></h3>
                {% endif %}
                <p class='pub_date'> {{ project.get_date }} </p>
            </li>
        {% endfor %}
        </ul>
    </nav>
</div>
{% else %}
    <p> No projects are available yet. Check again soon! </p>
{% endif %}

{% endblock %}

{% block ga %}
{% if GA_TRACKING_ID %}
  {% include "layouts/scripts/ga.html" %}
{% endif %}
{% endblock %}

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'layouts/base.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
    {% block extra_head %}{% endblock %}
</head>

<body>
    <div id='body_wrapper'>
        <div id='big_name'> <a href="{% url 'home:index' %}">Isaac Layton</a></div>
        <div class='social'>
            <span>
            <a href="https://github.com/isaaclayton">
              <img src="{% static 'images/GitHub-Mark-64px.png'%}" alt="Check out my GitHub!" class='logo'>
            </a>
            </span>
            <span>
            <a href="https://twitter.com/statchance">
              <img src="{% static 'images/Twitter_Logo_Blue.png'%}" alt="Check out my Twitter!" class='logo'>
            </a>
            </span>
            <span>
            <a href="https://www.linkedin.com/in/isaaclayton/">
              <img src="{% static 'images/In-2C-41px-R.png'%}" alt="Check out my Twitter!" class='logo'>
            </a>
            </span>
        </div>
        <div class='menu'>
            <nav>
                <a href="{% url 'home:index' %}">About</a>
                <a href="{% url 'projects:project_list' %}">Projects</a>
                <a href="{% url 'blog:post_list' %}">Blog</a>
                <a href="{% static 'pdf_files/resume.pdf' %}">Resume</a>
                <a href="{% url 'contact:email' %}">Contact</a>
            </nav>
        </div>

        <br>
        <hr>
        <main>
            {% block content %}
            {% endblock %}
            {% block ga %}
            {% endblock %}
        </main>
    </div>
</body>
    <footer>
        <p>&copy; Isaac Layton 2018.</p>
    </footer>
</html>